[Tech Debt] Remove Apple Watch code
litecoin-foundation/loafwallet-ios pull request #124
Opened 2020-10-14 23:03 UTC by kcw-grunt

- The Apple Watch Code is very old and has never been updated.
- There is a greater plan to remove superfluous code.
- If others ask to re-add it we will look again with the later versions

2020-10-15 17:11 UTC, kcw-grunt commented on loafwallet/src/ApplicationController.swift
>                  exchangeUpdater?.refresh(completion: {
Will eventually remove this call. : `exchangeUpdater?.refresh(completion: {})`

Currently there is a chain dependency on the labels so it has been kept in for the time being

2020-10-15 17:11 UTC, kcw-grunt commented on loafwallet/src/ApplicationController.swift
>              exchangeUpdater?.refresh(completion: {
Will eventually remove this call. : `exchangeUpdater?.refresh(completion: {})`

Currently there is a chain dependency on the labels so it has been kept in for the time being

2020-10-17 00:51 UTC, kcw-grunt commented
@mosadialiou 
Build is awaiting in App Store 
<img width="1025" alt="Screen Shot 2020-10-17 at 1 51 00 AM" src="https://user-images.githubusercontent.com/2899463/96324758-456f1000-101b-11eb-9b8f-f1ebf5c5643b.png">

2020-10-17 01:27 UTC, mosadialiou requested changes

2020-10-17 01:27 UTC, mosadialiou commented on loafwallet/src/Constants/Constants.swift
> +                            2. What version of software running on your mobile device (e.g.; Android 20, or 24 or iOS 13.7 or iOS 14)?</div>
There is no Android 20 or 24 instead it is Android 9, 10 and 11 (released september 8, 2020)

2020-10-17 07:46 UTC, kcw-grunt commented on loafwallet/src/Constants/Constants.swift
> +                            2. What version of software running on your mobile device (e.g.; Android 20, or 24 or iOS 13.7 or iOS 14)?</div>
Got it thanks. (These are meant to be examples and in fact I will give you a version for Android without iOS)

2020-10-18 23:02 UTC, mosadialiou approved these changes
LGTM

2020-10-18 23:08 UTC, merged