🦺 [Tech Debt] Update Podfile and Refacor build process
litecoin-foundation/loafwallet-ios pull request #144
Opened 2020-10-31 01:17 UTC by kcw-grunt

## Overview
There are upcoming projects that need a more updated versions of Cocopods , iOS versions and there are old remnants of code that was not used. This PR fixes some of that tech debt

## Summary of changes
- Set minimum value of iOS 13
- Removed unused SwiftyJSON
- Removed unused Watch Scheme
- re-added xcscheme
- removed non-used code
- added status badge in README

## Bitrise CI
Using Bitrise, the project now builds and runs tests which is the first step delivering more reliable code. This literally represents months of off and on work to debug the system.  Yay 🥳🍄

|First CI Build|
|-------------|
|<img width="835" alt="Screen Shot 2020-10-30 at 6 15 50 PM" src="https://user-images.githubusercontent.com/2899463/97767833-042b3580-1adc-11eb-95fe-dca4872051b5.png">|

2020-10-31 01:18 UTC, kcw-grunt commented on .gitignore
> -*.xcscheme
This line was causing issues for Bitrise b/c it relies on the uploaded scheme

2020-11-03 10:00 UTC, mosadialiou requested changes

2020-11-03 12:25 UTC, kcw-grunt commented on Podfile
> +platform :ios, '13.0'
Yes..Firebase has a bug and so the minimum is now 13.  I made a decision to move up as the remaining are now very trivial [iOS Version Distribution](https://gs.statcounter.com/ios-version-market-share/mobile-tablet/worldwide)

2020-11-03 12:25 UTC, kcw-grunt commented on Podfile
> -  pod 'Alamofire', '~> 4.7'
@mosadialiou: This was not being used since I put it in.  It is cruft.

2020-11-03 12:26 UTC, kcw-grunt commented on scripts/icon_versioning.sh
> -#!/bin/sh
@mosadialiou: This was not being used since I put it in. It is cruft.
Also Bitrise will be doing this automatically.

2020-11-03 12:27 UTC, kcw-grunt commented on .gitignore
> -.build/
Thats for Swift Packages...but let me take a look

2020-11-03 12:30 UTC, kcw-grunt commented on .gitignore
> -.build/
That was an extra declaration. It is still  there:
<img width="632" alt="Screen Shot 2020-11-03 at 4 28 05 AM" src="https://user-images.githubusercontent.com/2899463/97985569-4a5af000-1d8d-11eb-87e5-095e49f3e52f.png">

2020-11-03 13:18 UTC, mosadialiou commented on Podfile
> +platform :ios, '13.0'
ok

2020-11-03 13:19 UTC, mosadialiou commented on Podfile
> -  pod 'Alamofire', '~> 4.7'
ok

2020-11-03 13:19 UTC, mosadialiou commented on scripts/icon_versioning.sh
> -#!/bin/sh
ok

2020-11-03 13:24 UTC, mosadialiou commented on .gitignore
> -.build/
@kcw-grunt I meant `.build` folder which is different from `build`

2020-11-03 13:30 UTC, kcw-grunt commented on .gitignore
> -.build/
Sure but that is related to SPM....which we are not using.
# Xcode automatically generates this directory with a .xcworkspacedata file and xcuserdata
# hence it is not needed unless you have added a package configuration file to your project
# .swiftpm
But I can add it.

2020-11-03 15:03 UTC, mosadialiou approved these changes
LGTM

2020-11-03 16:16 UTC, merged