Warmfix/support litecoin foundation 146
litecoin-foundation/loafwallet-ios pull request #151
Opened 2020-11-17 13:15 UTC by kcw-grunt

2020-11-17 17:14 UTC, mosadialiou requested changes

2020-11-17 17:14 UTC, mosadialiou commented on loafwallet/src/Views/SendViewCells/AddressCell.swift
> +                            paste.trailingAnchor.constraint(equalTo: scan.leadingAnchor, constant: -5.0) ])
magic number here. Can't you use `C.padding`?

2020-11-17 17:14 UTC, mosadialiou commented on loafwallet/src/ViewControllers/RootModals/SendViewController.swift
> +        supportLitecoinFoundationCell.view.constrain([
is this well formatted? It's different from others

2020-11-17 17:14 UTC, mosadialiou commented on loafwallet/src/ViewControllers/RootModals/SendViewController.swift
> +            ///Paste in Support Litecoin Foundation address to textField
don't we want to track this event?

2020-11-17 17:14 UTC, mosadialiou commented on loafwallet/src/Strings/zh-Hant.lproj/Localizable.strings
> +"SupportTheFoundation.title" = "";
empty translation here

2020-11-17 17:14 UTC, mosadialiou commented on loafwallet/src/Strings/Base.lproj/Localizable.strings
> +"SupportTheFoundation.title" = "";
use the same translation for english here

2020-11-17 17:14 UTC, mosadialiou commented on loafwallet/src/Strings/Base.lproj/Localizable.strings
> +"Support.title" = "";
I think it's not used. If so to be removed

2020-11-17 17:14 UTC, mosadialiou commented on loafwallet/SupportLitecoinFoundationView.swift
> +                    .padding(.all,10)
Not well formatted. there is a space after `,`
BTW format the whole class

2020-11-18 17:05 UTC, kcw-grunt commented on loafwallet/src/SimpleRedux/ReduxState.swift
> +
This is the result of the Refactor.

2020-11-18 17:05 UTC, kcw-grunt commented on loafwallet/src/Extensions/UIColor+Extension.swift
> +
This is the result of the Refactor.

2020-11-18 17:07 UTC, kcw-grunt commented on loafwallet/src/Strings/ar.lproj/Localizable.strings
> +/* Donate to the articles */
Actually all of the donation strings should be removed

2020-11-18 17:22 UTC, kcw-grunt commented on loafwallet/src/Views/SendViewCells/AddressCell.swift
> +                            paste.trailingAnchor.constraint(equalTo: scan.leadingAnchor, constant: -5.0) ])
No...it only accepts an Int.  Added a double ability

2020-11-18 17:25 UTC, kcw-grunt commented on loafwallet/src/ViewControllers/RootModals/SendViewController.swift
> +        supportLitecoinFoundationCell.view.constrain([
This is a SwiftUI view but it should be the same as the others....just fixed the indentation.

2020-11-18 17:26 UTC, kcw-grunt commented on loafwallet/src/ViewControllers/RootModals/SendViewController.swift
> +            ///Paste in Support Litecoin Foundation address to textField
Good point.

2020-11-18 18:31 UTC, mosadialiou approved these changes
LGTM

2020-11-18 19:17 UTC, merged