[Feature Issue 154] Adding Unstoppable Domains functionality
litecoin-foundation/loafwallet-ios pull request #155
Opened 2020-11-21 13:15 UTC by kcw-grunt

## Overview
The biggest challenge for users of cryptocurrency is the fear that they will send their crypto to the **wrong** person.
[Unstoppable Domain](https://www.unstoppabledomains.com) solved this problem by mapping a custom domain name for a user that purchased it.  The user then can associate that domain name to an LTC Address.

## Approach
The ideal is to locate the functionality where it is most likely to be used. In this case it is to be in the Send modal.
Aside from the basic functionality some other testing and UI polishes was added.
- Added UD action to the SendViewController
- reformatted code in new SwiftUI views and viewModels
- Added more tests
- Updated UnstoppableDomainsView and Model details
- [UI Polish] Added images and localized strings

## Issue
#154 

## Video Clip
|Sample Action|
|---------------|
|![udgif](https://user-images.githubusercontent.com/2899463/99878187-84384d00-2bfb-11eb-9d25-c2dbbb725942.gif)|

2020-11-21 13:16 UTC, kcw-grunt commented on LWActivityIndicator.swift
> +//  LWActivityIndicator.swift
More SwiftUI!!!

2020-11-21 13:17 UTC, kcw-grunt commented on loafwallet/UstoppableDomainViewModel.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 6) {
This wait needs to be adjusted after we have a few 000 users

2020-11-21 13:20 UTC, kcw-grunt commented
@merenkoff

2020-11-22 15:26 UTC, mosadialiou requested changes

2020-11-22 15:26 UTC, mosadialiou commented on loafwallet/partner-keys.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Remove this file `partner-keys.plist` from git and committed files.

2020-11-22 15:26 UTC, mosadialiou commented on loafwallet/src/Constants/Constants.swift
> +    init(){
add space between `)` and `{`

2020-11-22 15:26 UTC, mosadialiou commented on loafwallet/src/Strings/ar.lproj/Localizable.strings
> +"Send.UnstoppableDomains.placeholder" = "";
what is the behavior when the app is run on a iPhone with arabic language? Will the text be empty?

2020-11-22 15:26 UTC, mosadialiou commented on loafwallet/src/Strings/fr.lproj/Localizable.strings
> +"Send.UnstoppableDomains.placeholder" = "Entrez un nom de domaine";
precise the valid domains (`.crypto` `.zil`)

2020-11-22 15:26 UTC, mosadialiou commented on loafwallet/src/Strings/it.lproj/Localizable.strings
> +"Send.UnstoppableDomains.placeholder" = "Immettere un nome di dominio";
precise the valid domains (`.crypto .zil`)

2020-11-22 15:26 UTC, mosadialiou commented on loafwallet/src/Strings/nl.lproj/Localizable.strings
> +"Send.UnstoppableDomains.placeholder" = "Voer een domeinnaam in";
precise the valid domains (`.crypto .zil`)

2020-11-22 15:26 UTC, mosadialiou commented on loafwallet/src/Strings/ru.lproj/Localizable.strings
> +"Send.UnstoppableDomains.placeholder" = "Введите доменное имя";
precise the valid domains (`.crypto .zil`)

2020-11-22 17:17 UTC, kcw-grunt commented on loafwallet/src/Strings/ar.lproj/Localizable.strings
> +"Send.UnstoppableDomains.placeholder" = "";
Yes... it's why it hasn't been done yet. Removing.

2020-11-23 14:00 UTC, merenkoff approved these changes
Small comment (please check). All other works with Unstoppable Domains looks ok.

2020-11-23 21:18 UTC, merenkoff commented on loafwallet/UstoppableDomainViewModel.swift
> +
Add a item of resolution library for retain properly, and reuse it in every call of our API

2020-11-23 21:18 UTC, merenkoff commented on loafwallet/UstoppableDomainViewModel.swift
> +                case .success(let returnValue):
```swift
self.isDomainResolving = false //seems like you need to set it false here. I am not read all logics in you codebase but the way seems it is necessary here. IMHO
```

2020-11-29 20:36 UTC, kcw-grunt commented on loafwallet/UstoppableDomainViewModel.swift
> +        guard let resolution = try? Resolution(providerUrl: providerURLString, network: "mainnet") else {
Ok...let me take a look

2020-11-29 22:10 UTC, kcw-grunt commented on loafwallet/UstoppableDomainViewModel.swift
> +        guard let resolution = try? Resolution(providerUrl: providerURLString, network: "mainnet") else {
Got it. Done.

2020-11-29 22:11 UTC, kcw-grunt commented on loafwallet/src/Constants/Constants.swift
> +    init(){
Done.

2020-11-29 22:29 UTC, kcw-grunt commented on loafwallet/src/Strings/fr.lproj/Localizable.strings
> +"Send.UnstoppableDomains.placeholder" = "Entrez un nom de domaine";
Updated

2020-11-29 22:30 UTC, kcw-grunt commented on loafwallet/src/Strings/it.lproj/Localizable.strings
> +"Send.UnstoppableDomains.placeholder" = "Immettere un nome di dominio";
Updated.

2020-11-29 22:30 UTC, kcw-grunt commented on loafwallet/src/Strings/nl.lproj/Localizable.strings
> +"Send.UnstoppableDomains.placeholder" = "Voer een domeinnaam in";
Updated.

2020-11-29 22:30 UTC, kcw-grunt commented on loafwallet/src/Strings/ru.lproj/Localizable.strings
> +"Send.UnstoppableDomains.placeholder" = "Введите доменное имя";
Updated.

2020-11-29 22:31 UTC, kcw-grunt commented on loafwallet/UstoppableDomainViewModel.swift
> +                case .success(let returnValue):
This is because the we can't assume the timeout...this stops the activity view

2020-11-30 00:32 UTC, mosadialiou requested changes

2020-11-30 00:32 UTC, mosadialiou commented on TestPlayground.playground/Contents.swift
> +import SwiftUI
file to be removed!

2020-11-30 00:32 UTC, mosadialiou commented on TestPlayground.playground/contents.xcplayground
> +<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
file to be removed!

2020-11-30 00:32 UTC, mosadialiou commented on loafwallet/src/Strings/Base.lproj/Localizable.strings
> +"Send.enterLTCAddress" = "Enter an LTC Address";
I think we should write `Enter a LTC address`

2020-11-30 00:32 UTC, mosadialiou commented on loafwallet/src/Strings/en.lproj/Localizable.strings
> +"Send.enterLTCAddress" = "Enter an LTC Address";
`Enter a LTC address`

2020-11-30 00:32 UTC, mosadialiou commented on loafwallet/SocialView.swift
> +//
are we really using this view?!

2020-11-30 00:32 UTC, mosadialiou commented on loafwallet/SocialViewModel.swift
> +//
are we really using this class?!

2020-12-06 16:23 UTC, kcw-grunt commented on TestPlayground.playground/Contents.swift
> +import SwiftUI
done.

2020-12-06 16:24 UTC, kcw-grunt commented on TestPlayground.playground/contents.xcplayground
> +<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
done.

2020-12-06 16:24 UTC, kcw-grunt commented on loafwallet/SocialView.swift
> +//
removed.

2020-12-06 16:24 UTC, kcw-grunt commented on loafwallet/SocialViewModel.swift
> +//
removed.

2020-12-06 16:25 UTC, kcw-grunt commented on loafwallet/src/Strings/Base.lproj/Localizable.strings
> +"Send.enterLTCAddress" = "Enter an LTC Address";
Done.

2020-12-06 16:26 UTC, kcw-grunt commented on loafwallet/src/Strings/en.lproj/Localizable.strings
> +"Send.enterLTCAddress" = "Enter an LTC Address";
Done

2020-12-06 23:35 UTC, mosadialiou requested changes

2020-12-06 23:35 UTC, mosadialiou commented on loafwallet/ResolutionModel.swift
> +        var keypath: String = ""
remove this line and at line 26 AND just add `let` before `keypath`

2020-12-06 23:35 UTC, mosadialiou commented on loafwallet/ResolutionModel.swift
> +                print("Unstoppable Domains Error: \(String(describing: self.resolution))")
can't you write this instead 
`print("Unstoppable Domains Error: \(self.resolution)")`

2020-12-06 23:35 UTC, mosadialiou commented on loafwallet/UnstoppableDomainViewModel.swift
> +                                self.ltcAddress = returnValue
this line can be outside of the block

2020-12-06 23:57 UTC, kcw-grunt commented on loafwallet/ResolutionModel.swift
> +        var keypath: String = ""
This is because the variable needs to exist outside the scope..

2020-12-06 23:58 UTC, kcw-grunt commented on loafwallet/ResolutionModel.swift
> +                print("Unstoppable Domains Error: \(String(describing: self.resolution))")
This is a recommendation from Xcode to resolve the warning

2020-12-07 00:45 UTC, kcw-grunt commented on loafwallet/UnstoppableDomainViewModel.swift
> +                                self.ltcAddress = returnValue
This is a neat trick that makes the resolution quicker....that's why it was all placed in the block.  Eventually I want to measure the average time for resolution for the domain

2020-12-07 00:53 UTC, kcw-grunt commented on loafwallet/ResolutionModel.swift
> +        var keypath: String = ""
Ok updated.

2020-12-07 11:39 UTC, mosadialiou commented on loafwallet/UnstoppableDomainViewModel.swift
> +                                self.ltcAddress = returnValue
ok

2020-12-07 11:55 UTC, mosadialiou requested changes

2020-12-07 11:55 UTC, mosadialiou commented on loafwallet/src/Strings/en.lproj/Localizable.strings
> +"Send.enterLTCAddress" = "Enter an LTC Address";
Not yet!

2020-12-07 11:55 UTC, mosadialiou commented on loafwallet/src/Strings/Base.lproj/Localizable.strings
> +"Send.enterLTCAddress" = "Enter an LTC Address";
Not yet!

2020-12-07 13:37 UTC, mosadialiou approved these changes
LGTM
Well done!!!

2020-12-07 13:54 UTC, merged

2020-12-25 11:45 UTC, mosadialiou commented on loafwallet/UnstoppableDomainView.swift
> +                                Text("Lookup")
@kcw-grunt The text "Lookup" is not translated