[Bugfix] Fix buy tab: Simplex urls
litecoin-foundation/loafwallet-ios pull request #157
Opened 2020-11-22 14:28 UTC by kcw-grunt

## Problem
The LW backend has been updated with a new url and service and the vales do not currently work when the user will try to sort out the issue.

## Approach 
Run tests for the new service by starting with staging/sandbox
- Run end to end test
- Add in the constants for production

## Video Clips
|Completed Transaction|
|-----------------------|
|![sandbaox](https://user-images.githubusercontent.com/2899463/99906412-ec0b9800-2cce-11eb-9c6a-2c5ebe5c9965.gif)|

2020-11-22 15:38 UTC, mosadialiou requested changes

2020-11-22 15:38 UTC, mosadialiou commented on loafwallet/BRAPIClient+Wallet.swift
> +private let fallbackRatesURL = "https://api-stage.lite-wallet.org/rates"
can you share here the code where `ratesURL` and `fallbackRatesURL` are used?
From my understanding I would have just write something like this:
    
#if DEBUG
    static let ratesURL = "https://api-stage.lite-wallet.org/rates"
    #else
    static let ratesURL = "https://api-prod.lite-wallet.org/rates"
    #endif

Thoughts?

2020-11-22 15:38 UTC, mosadialiou commented on loafwallet/partner-keys.plist
> +<?xml version="1.0" encoding="UTF-8"?>
to be removed from git and committed files

2020-11-22 18:07 UTC, kcw-grunt commented on loafwallet/BRAPIClient+Wallet.swift
> +private let fallbackRatesURL = "https://api-stage.lite-wallet.org/rates"
Good point.  There should be served by the API server.
I substituted the url and expected it to fail
@gneo54 is this endpoint _(https://api-stage.lite-wallet.org/v1/rates)_ ready?

2020-11-22 18:10 UTC, kcw-grunt commented on loafwallet/BRAPIClient+Wallet.swift
> +private let fallbackRatesURL = "https://api-stage.lite-wallet.org/rates"
@mosadialiou we can just do this:
APIServer.baseUrl + "v1/rates"
After the confirmation

2020-11-22 21:45 UTC, mosadialiou commented on loafwallet/BRAPIClient+Wallet.swift
> +private let fallbackRatesURL = "https://api-stage.lite-wallet.org/rates"
Yes sure!

2020-11-23 14:55 UTC, kcw-grunt commented
@gneo54
@mosadialiou :

Ran another sandbox run and was successfully completed.

|Sandbox-Run: 2|
|----------------|
|![sandbox-run-2](https://user-images.githubusercontent.com/2899463/99976871-e0d26e00-2d9b-11eb-957f-37842594e6d1.gif)|

2020-11-30 20:19 UTC, merged

2020-12-01 12:06 UTC, mosadialiou commented on loafwallet/BRAPIClient+Wallet.swift
> +        let request = isFallback ? URLRequest(url: URL(string: fallbackRatesURL)!) : URLRequest(url: URL(string: APIServer.baseUrl + "v1/rates")!)
When we get a chance, just write this:
let request = URLRequest(url: URL(string: isFallback ? fallbackRatesURL : APIServer.baseUrl + "v1/rates")!)