[Tech Debt] Update readme.md
litecoin-foundation/loafwallet-ios pull request #174
Opened 2020-12-21 23:29 UTC by kcw-grunt

2020-12-22 00:39 UTC, mosadialiou requested changes

2020-12-22 00:39 UTC, mosadialiou commented on pages/development.md
> +6. A new PR from the `master` to `develop` is created
should be: `

6. A new PR from the `release/v2.9.0` to `develop` is created`

2021-01-20 10:22 UTC, mosadialiou requested changes
LGTM 
However the destination branch of the PR has to be `develop`

2021-01-20 10:31 UTC, kcw-grunt commented
> LGTM
> However the destination branch of the PR has to be `develop`

Cool.  Changed.  Tx.

2021-01-20 10:38 UTC, mosadialiou approved these changes
LGTM

2021-01-20 11:18 UTC, merged