[Feature] Litecoin card v1
litecoin-foundation/loafwallet-ios pull request #180
Opened 2021-01-05 11:32 UTC by kcw-grunt

## Overview
This is work has been in progress for over 1 year and we are now ready to release it as an **ALPHA** to our users.  This feature allows users to Register and Login to the Litecoin Card (https://litecoin-card.com/)

The next step is to add transfer and syncing capabilities

## Approach
The demo of this work used a combination of UIKit versions with programmitic and Storyboard layouts.  The blockcard was not yet  completely available.  To allow better visualizations and quicker developments (as the risk of an incomplete framework) SwiftUI and MVVM is used primarily in this work.

## Components
Some parts of the work can be described in these areas:
- Hybrid UIKit / SwiftUI integrations
- Legacy mockups used as a guide but will be polished further 
- Using the Partner Library API

## Clips

| Before | After|
|--------|-----|
|![v2 8 30-fix](https://user-images.githubusercontent.com/2899463/103461848-3560f580-4d19-11eb-826c-cfddb9dba271.gif)|![CardV2](https://user-images.githubusercontent.com/2899463/103461947-d485ed00-4d19-11eb-88ec-6e20661d4fc9.gif)|

2021-01-07 10:32 UTC, mosadialiou requested changes

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/src/Strings/Base.lproj/Localizable.strings
> +<<<<<<< HEAD
remaining conflict to fix

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/src/FlowControllers/URLController.swift
> +//        case "bitid":
we should remove this dead code

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/src/FlowControllers/URLController.swift
> +//    private func handleBitId(_ url: URL) {
we should remove this dead code

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/src/Extensions/UINavigationController+Extension.swift
> +    override open func viewDidLoad() {
remove this overridden function

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/src/Constants/Strings.swift
> + //DEV: Removing eventually
we should remove this dead code

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/TransactionsViewController.swift
> +//struct TransactionsSwiftUIView: UIViewControllerRepresentable {
to be removed!

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/TabBarViewController.swift
> +                item.title = "NO-TITLE"
OR just maybe an empty title

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/RegistrationView.swift
> +
a lot of extra lines. why?

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/RegistrationViewModel.swift
> +        if testUserID == nil {
do you still want to keep this `testUserID`?

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/Keychain.swift
> +//
to be removed

2021-01-07 10:32 UTC, mosadialiou commented on Podfile
> +  pod 'KeychainAccess', '~> 4.2'
why using a 3rd party lib here. There is no Keychain API within the iOS SDK?

2021-01-07 10:32 UTC, mosadialiou commented on loafwallet/DataValidation.swift
> +        guard !value.isEmpty else { throw ValidationError("Must not be empty") }
Have to localize all the validation errors.

2021-01-07 11:45 UTC, kcw-grunt commented on loafwallet/src/Strings/zh-Hant.lproj/Localizable.strings
> +>>>>>>> origin/develop
Thanks.

2021-01-07 12:11 UTC, kcw-grunt commented on Podfile
> +  pod 'KeychainAccess', '~> 4.2'
It's just a wrapper to the Keychain API.  This will be refactored in v2

2021-01-07 12:12 UTC, kcw-grunt commented on loafwallet/DataValidation.swift
> +        guard !value.isEmpty else { throw ValidationError("Must not be empty") }
Good catch!

2021-01-07 13:56 UTC, mosadialiou commented on Podfile
> +  pod 'KeychainAccess', '~> 4.2'
OK sounds good! But let's avoid using a 3rd party lib to access the Keychain.
BTW can you create an issue for that.

2021-01-07 14:27 UTC, kcw-grunt commented on Podfile
> +  pod 'KeychainAccess', '~> 4.2'
Sure...totally agreed.

2021-01-07 14:30 UTC, kcw-grunt commented on Podfile
> +  pod 'KeychainAccess', '~> 4.2'
https://github.com/litecoin-foundation/loafwallet-ios/issues/181

2021-01-07 17:08 UTC, kcw-grunt commented on loafwallet/RegistrationViewModel.swift
> +        if testUserID == nil {
renamed and polished

2021-01-07 17:11 UTC, kcw-grunt commented on loafwallet/PartnerAPIManager.swift
> +    override init() {
it's needed by swift

2021-01-08 00:56 UTC, mosadialiou requested changes

2021-01-08 00:56 UTC, mosadialiou commented on loafwallet/LoginCardAlertView.swift
> +                                message: "Login...")
localize `Login...`

2021-01-08 01:07 UTC, mosadialiou requested changes

2021-01-08 01:07 UTC, mosadialiou commented on loafwallet/DataValidation.swift
> +        guard !value.isEmpty else { throw ValidationError(S.LitecoinCard
You can have this in just one line for better readability. What the formatter suggests?

2021-01-08 11:23 UTC, kcw-grunt commented on loafwallet/LoginCardAlertView.swift
> +                                message: "Login...")
No...that's for just a developers preview.

2021-01-08 11:24 UTC, kcw-grunt commented on loafwallet/DataValidation.swift
> +        guard !value.isEmpty else { throw ValidationError(S.LitecoinCard
The formatter that i'm using 'swiftformat' wraps `.` to reduce lines to 80 chars or less.  This is by design

2021-01-08 11:52 UTC, mosadialiou commented on loafwallet/DataValidation.swift
> +        guard !value.isEmpty else { throw ValidationError(S.LitecoinCard
OK

2021-01-08 11:52 UTC, mosadialiou commented on loafwallet/LoginCardAlertView.swift
> +                                message: "Login...")
ok

2021-01-08 11:55 UTC, mosadialiou approved these changes
LGTM

2021-01-08 13:16 UTC, merged