[Merge v3.0.0] into Develop
litecoin-foundation/loafwallet-ios pull request #184
Opened 2021-01-08 15:53 UTC by kcw-grunt

- version bump

2021-01-09 23:47 UTC, mosadialiou requested changes

2021-01-09 23:47 UTC, mosadialiou commented on loafwallet/CardView.swift
> +                                didCompleteLogin ? geometry.size.width * 0.4 :
Just curious: did you do the line break yourself OR it's the formatter?

2021-01-09 23:47 UTC, mosadialiou commented on loafwallet/CardView.swift
> +                            if currentEmail.count < 4 ||  !registrationModel.isEmailValid(emailString: currentEmail) {
replace if else with:
`isEmailValid = currentEmail.count > 4 && registrationModel.isEmailValid(emailString: currentEmail)`

2021-01-09 23:47 UTC, mosadialiou commented on loafwallet/CardView.swift
> +                                    if !registrationModel.isPasswordValid(passwordString:  currentPassword) {
replace `if else` with 

`isPasswordValid = registrationModel.isPasswordValid(passwordString:  currentPassword)`

2021-01-09 23:47 UTC, mosadialiou commented on loafwallet/CardView.swift
> +                                    if !registrationModel.isPasswordValid(passwordString:  currentPassword) {
replace `if else` with

`isPasswordValid = registrationModel.isPasswordValid(passwordString:  currentPassword)`

2021-01-09 23:47 UTC, mosadialiou commented on loafwallet/RegistrationViewModel.swift
> +                return  dataString == "US" ?  true : false
write just:

`dataString == "US"`

2021-01-09 23:47 UTC, mosadialiou commented on loafwallet/RegistrationViewModel.swift
> +        if  self.isDataValid(dataType: .genericString, data: first) &&
as a general remark, `self.` is not needed. Just write the function's name.

2021-01-09 23:54 UTC, kcw-grunt commented
This is stale...closing once v3.0.0 is approved.

2021-01-10 00:14 UTC, kcw-grunt commented on loafwallet/CardView.swift
> +                                didCompleteLogin ? geometry.size.width * 0.4 :
manual but the formatter will do the same.

2021-01-10 00:15 UTC, kcw-grunt commented on loafwallet/CardView.swift
> +                                    if !registrationModel.isPasswordValid(passwordString:  currentPassword) {
no need to set the variable...its changed by the model...

2021-01-10 00:15 UTC, kcw-grunt commented on loafwallet/CardView.swift
> +                                    if !registrationModel.isPasswordValid(passwordString:  currentPassword) {
no need to set the variable...its changed by the model...

2021-01-10 00:18 UTC, kcw-grunt commented on loafwallet/RegistrationViewModel.swift
> +                return  dataString == "US" ?  true : false
I really really like ternary operators...I need the gentle jog of of memory of operation.   Even though we can leave it shorter, this method has a good reminder of the ideal logic.  That's why I put it in.

2021-01-10 00:37 UTC, mosadialiou commented on loafwallet/CardView.swift
> +                                didCompleteLogin ? geometry.size.width * 0.4 :
hmmm I get it. I don't think the formatter will do the same. Can you put it in 1 line and apply the formatter. If you see a line break so you are right.

2021-01-10 02:00 UTC, mosadialiou approved these changes
LGTM

2021-01-10 02:02 UTC, merged