[Bugfix]UD resolved address / got callback
litecoin-foundation/loafwallet-ios pull request #193
Opened 2021-01-12 20:56 UTC by kcw-grunt

- Added a dispatch group
- Fixed the bug by  adding wait to the group from (@JohnnyJumper)
- Refactored partner plist

2021-01-12 21:41 UTC, mosadialiou requested changes

2021-01-12 21:41 UTC, mosadialiou commented on loafwallet/UnstoppableDomainViewModel.swift
> +class ResolutionModel: NSObject {
you have to delete this class. it's not used!

2021-01-12 21:41 UTC, mosadialiou commented on loafwallet/UnstoppableDomainViewModel.swift
> +        let group = DispatchGroup()
can you extract a method?

2021-01-12 21:41 UTC, mosadialiou commented on loafwallet/ResolutionModel.swift
>  import Foundation
we should remove this class, right?

2021-01-12 21:53 UTC, kcw-grunt commented on loafwallet/ResolutionModel.swift
>  import Foundation
my bad...removing

2021-01-12 21:54 UTC, kcw-grunt commented on loafwallet/UnstoppableDomainViewModel.swift
> +        let group = DispatchGroup()
Sorry...I'm not understanding

2021-01-12 21:57 UTC, mosadialiou commented on loafwallet/UnstoppableDomainViewModel.swift
> +        let group = DispatchGroup()
create a function or method to export all this new code

2021-01-12 21:58 UTC, mosadialiou commented on loafwallet/UnstoppableDomainViewModel.swift
> +        let group = DispatchGroup()
you can call the function or method `resolveDomain`

2021-01-12 22:58 UTC, kcw-grunt commented on loafwallet/UnstoppableDomainViewModel.swift
> +        let group = DispatchGroup()
yeah in troubleshooting I put it all there. Let me move it.

2021-01-13 11:59 UTC, mosadialiou requested changes

2021-01-13 11:59 UTC, mosadialiou commented on loafwallet/UnstoppableDomainViewModel.swift
> +public typealias KeyPathResult = (Result<String, DocumentError>) -> Void
where do you use `KeyPathResult`?

2021-01-13 12:43 UTC, kcw-grunt commented on loafwallet/UnstoppableDomainViewModel.swift
> +public typealias KeyPathResult = (Result<String, DocumentError>) -> Void
removed (as well as the DocumentError enum)

2021-01-13 12:53 UTC, mosadialiou requested changes

2021-01-13 12:53 UTC, mosadialiou commented on loafwallet/UnstoppableDomainViewModel.swift
> +    private var resolution: Resolution?
not used! delete it and we are good

2021-01-13 12:54 UTC, kcw-grunt commented on loafwallet/UnstoppableDomainViewModel.swift
> +    private var resolution: Resolution?
ugh..caught me!

2021-01-13 13:02 UTC, mosadialiou approved these changes
LGTM

2021-01-13 13:04 UTC, merged