[Bugfix] Opened the password range: 24 chars
litecoin-foundation/loafwallet-ios pull request #222
Opened 2021-02-08 20:19 UTC by kcw-grunt

## Issue
Users of version 1 had an issue with the password blocking the password making them unable to login to Litecoin Card .

## Approach
Open the range to a wide number `24`

2021-02-08 20:20 UTC, kcw-grunt commented
cc: @zenithquinn this is a result of some user feedback.

2021-02-14 11:30 UTC, mosadialiou requested changes

2021-02-14 11:30 UTC, mosadialiou commented on loafwallet/RegistrationViewModel.swift
> +        guard (passwordString.count >= 6 && passwordString.count <= 24) else {
@kcw-grunt I don't know what was the reason to limit the password to 10 or even 24 chars. I do think we just have to check the min number of chars. If a user want he can create a 50 chars password length.

2021-02-16 23:27 UTC, kcw-grunt commented on loafwallet/RegistrationViewModel.swift
> +        guard (passwordString.count >= 6 && passwordString.count <= 24) else {
yeah...the partner are not giving details....I
'll take that line out.

2021-02-17 13:48 UTC, mosadialiou commented on loafwallet/RegistrationViewModel.swift
> -        guard (passwordString.count >= 6 && passwordString.count <= 10) else {
@kcw-grunt The maximum number of characters is not needed but I do think we should keep the minimum characters at 6. Thoughts?

2021-02-17 14:29 UTC, kcw-grunt commented on loafwallet/RegistrationViewModel.swift
> -        guard (passwordString.count >= 6 && passwordString.count <= 10) else {
The Ternio team haven't provided a schema yet. Standby on this. I will update the PR soon.

2021-02-17 14:43 UTC, mosadialiou commented on loafwallet/RegistrationViewModel.swift
> -        guard (passwordString.count >= 6 && passwordString.count <= 10) else {
ok

2021-03-14 23:32 UTC, mosadialiou approved these changes
LGTM

2021-03-14 23:48 UTC, merged