[Tech Debt] Added “Balance” label with localizations
litecoin-foundation/loafwallet-ios pull request #232
Opened 2021-02-23 17:34 UTC by kcw-grunt

- Set the layout

2021-02-23 19:43 UTC, mosadialiou requested changes

2021-02-23 19:43 UTC, mosadialiou commented on loafwallet/Storyboards/Main.storyboard
> +                                    <tabBarItem title="History" image="history_icon" selectedImage="history_icon" id="qwA-9l-CfE" userLabel="History"/>
@kcw-grunt Do you really want to remove the `tag="0"` attribute?

2021-02-23 19:43 UTC, mosadialiou commented on loafwallet/src/Strings/es.lproj/Localizable.strings
> +"ManageWallet.balance" = "Equilibrio";
Recheck the translation. I think `Saldo` is more appropriated

2021-02-23 19:43 UTC, mosadialiou commented on loafwallet/src/Strings/fr.lproj/Localizable.strings
> +"ManageWallet.balance" = "Équilibre";
`Solde` is more suited

2021-02-23 19:43 UTC, mosadialiou commented on loafwallet/src/Strings/it.lproj/Localizable.strings
> +"ManageWallet.balance" = "Equilibrio";
Recheck please. Put it in a whole phrase to see the correct translation

2021-02-23 19:43 UTC, mosadialiou commented on loafwallet/src/Strings/pt.lproj/Localizable.strings
> +"ManageWallet.balance" = "Equilíbrio";
Please recheck the translation.

2021-02-25 22:19 UTC, kcw-grunt commented on loafwallet/Storyboards/Main.storyboard
> +                                    <tabBarItem title="History" image="history_icon" selectedImage="history_icon" id="qwA-9l-CfE" userLabel="History"/>
Xcode corrupted this.

2021-02-25 23:07 UTC, mosadialiou approved these changes
LGTM

2021-02-25 23:13 UTC, merged