🦺[Tech debt] Add card disclaimer toast
litecoin-foundation/loafwallet-ios pull request #240
Opened 2021-03-05 00:17 UTC by kcw-grunt

2021-03-06 23:35 UTC, mosadialiou requested changes

2021-03-06 23:35 UTC, mosadialiou commented on loafwallet/src/Strings/fr.lproj/Localizable.strings
> +"LitecoinCard.Disclaimer.bullets" = "- Nouvelle inscription\n- Connexion (compte existant)\n- Aucun solde affiché\n- Pas de transfert\n- Seulement nous";
Wrong translation. Replace "Seulement nous" -> "États-Unis uniquement"

2021-03-06 23:35 UTC, mosadialiou commented on loafwallet/src/Strings/es.lproj/Localizable.strings
> +"LitecoinCard.Disclaimer.bullets" = "- Nuevo registro\n- Ingrese cuenta existente)\n- No se muestra saldo\n- Sin transferencia\n- Solo nosotros";
Wrong translation: "Estados Unidos solamente" is more suited than "Solo nosotros"

2021-03-06 23:35 UTC, mosadialiou commented on loafwallet/src/Strings/pt.lproj/Localizable.strings
> +"LitecoinCard.Disclaimer.bullets" = "- Novo registro\n- Entrar em uma conta existente)\n- Nenhum saldo mostrado\n- Sem transferência\n- Apenas nós";
Wrong translation: "Apenas estados unidos" is more suited than "Apenas nós"

2021-03-06 23:44 UTC, mosadialiou commented
@kcw-grunt Make sure all the changes in this commit https://github.com/litecoin-foundation/loafwallet-android/commit/9c0a5305278385df5df1ad9aa5cbff6148149469 are done!

2021-03-07 16:35 UTC, kcw-grunt commented on loafwallet/src/Strings/fr.lproj/Localizable.strings
> +"LitecoinCard.Disclaimer.bullets" = "- Nouvelle inscription\n- Connexion (compte existant)\n- Aucun solde affiché\n- Pas de transfert\n- Seulement nous";
D'accord.  Merci beaucoup

2021-03-07 17:00 UTC, mosadialiou approved these changes
LGTM

2021-03-07 17:02 UTC, merged