🥳[Feature]  Add moonpay
litecoin-foundation/loafwallet-ios pull request #245
Opened 2021-03-14 23:11 UTC by kcw-grunt

## Goal
Add another way to buy Litecoin  through our partner, Moonpay

## Screenshot

|Before|After|
|-------|-----|
|![after-newfiats](https://user-images.githubusercontent.com/2899463/111087611-785df700-851a-11eb-8ff5-7e813e397733.gif)|![moonpay](https://user-images.githubusercontent.com/2899463/111087597-65e3bd80-851a-11eb-8fef-229cf9c22282.gif)|

2021-03-17 16:15 UTC, mosadialiou requested changes

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/da.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/de.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/es.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/fr.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/id.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/it.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/ja.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/ko.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/nl.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/pt.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/ru.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/sv.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/zh-Hans.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/src/Strings/zh-Hant.lproj/Localizable.strings
> +"BuyCenter.moonpayFinancialDetails" = "";
missing translations

2021-03-17 16:15 UTC, mosadialiou commented on loafwallet/BuyWKWebViewController.swift
> +        switch partnerName {
Why using `partnerName` since this class is only for `Simplex` partner?
I think you should delete all references to another partner and just assume it's just Simplex until it's used for another one.

2021-04-01 18:16 UTC, kcw-grunt commented on loafwallet/BuyWKWebViewController.swift
> +        switch partnerName {
good point

2021-04-02 13:47 UTC, mosadialiou requested changes

2021-04-02 13:47 UTC, mosadialiou commented on loafwallet/BuyWKWebViewController.swift
> +    var partnerName: PartnerName?
`partnerName` is not used! so it can be removed.

2021-04-02 13:47 UTC, mosadialiou commented on loafwallet/BuyTableViewController.swift
> +enum PartnerName {
It seems like this enum is only used by Simplex. We can remove it.

2021-04-02 15:18 UTC, kcw-grunt commented on loafwallet/BuyWKWebViewController.swift
> +    var partnerName: PartnerName?
🧹

2021-04-02 15:19 UTC, kcw-grunt commented on loafwallet/BuyTableViewController.swift
> +enum PartnerName {
🎉🤔🧹

2021-04-02 15:46 UTC, mosadialiou approved these changes
LGTM

2021-04-05 09:46 UTC, kcw-grunt commented
## Test Staging Screenshots
|Success|Failed|
|![moonpaysuccess-stage](https://user-images.githubusercontent.com/2899463/113561117-ff732c00-95fb-11eb-91a2-2461a26be94e.gif)|![moonpay-fail-stage](https://user-images.githubusercontent.com/2899463/113561228-29c4e980-95fc-11eb-9ed0-bb5bc997f29a.gif)|

2021-04-05 09:47 UTC, merged