🥳[Feature] Add live balance
litecoin-foundation/loafwallet-ios pull request #252
Opened 2021-04-01 17:20 UTC by kcw-grunt

## Feature
When the user logs into LitecoinCard, the balance is retrieved and updated in the CardLoggedInView
Closes #242 

## Commits
- Added wallet detail and live balance
- Cleaned up the dev notes & response reference
- Add model using Codable
- Added test to check the wallet details
- Updated the text action

## Screenshots

|Before|After|
|-----|-------|
|![befiorelivebalance](https://user-images.githubusercontent.com/2899463/113330526-bc246f00-9316-11eb-939f-3b0044db8d82.gif)|![afterlivebalance](https://user-images.githubusercontent.com/2899463/113329955-1f61d180-9316-11eb-97a6-da47ff87e814.gif)|

2021-04-04 15:58 UTC, mosadialiou requested changes
some minor changes

2021-04-04 15:58 UTC, mosadialiou commented on loafwallet/CardLoggedInView.swift
> +                        self.balanceText = "Ł" + String(format:"%6.4f",availableBalance)
@kcw-grunt maybe you should use the same method used to format the user's balance

2021-04-04 15:58 UTC, mosadialiou commented on loafwallet/CardWalletDetails.swift
> +        balance = try! container.decode(Float.self, forKey: .balance)
It seems like the app will crash if `balance` field is missing from the JSON. please implement an optional decoding here.

2021-04-04 19:25 UTC, kcw-grunt commented on loafwallet/CardLoggedInView.swift
> +                        self.balanceText = "Ł" + String(format:"%6.4f",availableBalance)
Do you mean in the viewModel? This is a model/state management feature in combine where any changes of the parameters of the viewModel are automatically updated.  Since we may have to show different states of the users balance, the model stores the values in the same type as sent from the endpoint (Float type)  

Ultimately, other objects may need to access those values and convert.  So, I chose to do the formatting just prior to display (here in this `onreceive` block) because it is cleaner to pass the value and format based on usage...outside the viewModel.

2021-04-04 19:29 UTC, kcw-grunt commented on loafwallet/CardWalletDetails.swift
> +        balance = try! container.decode(Float.self, forKey: .balance)
Actually, if  any of those values are missing it will crash.  The way it works is we have the forced unwrap **and** the tests in `CardWalletTests` check to see if the schema changed at all, if it fails, we reach out to  _`Corey`_ at Ternio

2021-04-04 23:54 UTC, mosadialiou commented on loafwallet/CardWalletDetails.swift
> +        balance = try! container.decode(Float.self, forKey: .balance)
Yeah I see what you mean. but as a dev we have to make sure the app won't crashes if the API change.
For example, in Android if any of those values are missing the app will not crash. So I think we should have something like this in iOS too.

2021-04-05 00:08 UTC, mosadialiou commented on loafwallet/CardLoggedInView.swift
> +                        self.balanceText = "Ł" + String(format:"%6.4f",availableBalance)
Yeah you are doing the good thing. I just suggest to reuse the same method we are using to format the balance in the home view.

2021-04-05 00:09 UTC, mosadialiou requested changes
Responded to your comments

2021-04-05 18:10 UTC, kcw-grunt commented on loafwallet/CardWalletDetails.swift
> +        balance = try! container.decode(Float.self, forKey: .balance)
Sure...this is an optional so I can switch it.  The risk is won't notify us when there is a failure.

2021-04-05 18:26 UTC, kcw-grunt commented on loafwallet/CardLoggedInView.swift
> +                        self.balanceText = "Ł" + String(format:"%6.4f",availableBalance)
@mosadialiou do you mean in the header view?  The problem with that is there is not enough space there. 
Also, I'm removing the current balance in issue #248

2021-04-05 19:37 UTC, mosadialiou commented on loafwallet/CardWalletDetails.swift
> +        balance = try! container.decode(Float.self, forKey: .balance)
It's not optional because the app will crash if any of those values are missing. You can add a log event to notify us when there's a parsing failure. The important thing is that the app won't crash.

2021-04-05 19:39 UTC, mosadialiou commented on loafwallet/CardLoggedInView.swift
> +                        self.balanceText = "Ł" + String(format:"%6.4f",availableBalance)
Yes the `balance / local` fiat value in the header view. You know what?! We can live with it... will refactor later.

2021-04-05 20:19 UTC, mosadialiou approved these changes
LGTM

2021-04-06 12:23 UTC, merged