🦺 [Tech Debt] Changed password criteria
litecoin-foundation/loafwallet-ios pull request #259
Opened 2021-04-07 22:13 UTC by kcw-grunt

## Why
Partner passed the password criteria and it needed to match the Dashboard criteria

## Commits
- 1 Capital letter, 1 number, 8 min chars, accepts special chars
- Added tests

2021-04-08 17:09 UTC, mosadialiou requested changes
The code LGTM but to avoid any confusion we have to tell the user that the password has to be `8 chars minimum, 1 Capital letter and 1 number, accepts special characters`

2021-04-08 19:44 UTC, kcw-grunt commented
> The code LGTM but to avoid any confusion we have to tell the user that the password has to be `8 chars minimum, 1 Capital letter and 1 number, accepts special characters`

Agreed! It only took 1 year to get the info.  I wrote an issue for an improvement: #260

2021-04-09 09:31 UTC, mosadialiou requested changes

2021-04-09 09:31 UTC, mosadialiou commented on loafwallet/RegistrationViewModel.swift
> +        if try! NSRegularExpression(pattern: "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d$&+,:;=?@#|'<>.^*()%!-]{8,}$", options: .caseInsensitive)
@kcw-grunt revert this change

2021-04-09 09:31 UTC, mosadialiou commented on loafwallet/RegistrationViewModel.swift
> +        guard passwordString.count >= 8 else {
@kcw-grunt revert this change for now

2021-04-09 09:31 UTC, mosadialiou commented on loafwallet/RegistrationViewModel.swift
> +    /// - Parameter passwordString: 8 chars minimum, 1 Capital letter and 1 number, accepts special characters
@kcw-grunt revert this change

2021-04-09 09:31 UTC, mosadialiou commented on loafwalletTests/Class Tests/LitecoinCardTests/RegistrationViewModelTests.swift
> +    func testIsPasswordValid() throws {
@kcw-grunt revert all changes in this file

2021-04-09 09:48 UTC, kcw-grunt commented on loafwallet/RegistrationViewModel.swift
> +        guard passwordString.count >= 8 else {
oh yeah...good point.

2021-04-09 09:59 UTC, mosadialiou requested changes

2021-04-09 09:59 UTC, mosadialiou commented on loafwalletTests/Class Tests/LitecoinCardTests/RegistrationViewModelTests.swift
> +    func testIsPasswordValid() throws {
@kcw-grunt you didn't revert the changes! put the file back as it was before the changes

2021-04-09 10:28 UTC, mosadialiou approved these changes
LGTM

2021-04-09 10:34 UTC, merged